Issue #3: Add initial doc infrastructure
Issue #3: Add initial doc infrastructure

## What has been done

This MR adds documentation generator along with tests for the docs directory structure.

Full training that explains things done in this MR is here: https://swedishembedded.com/zephyr-getting-started-documentation-generation/

## Proof

- scripts/check

## Known issues/limitations

* Does not add checks for making sure all tests and samples are documented.

Closes #3

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -4,6 +4,8 @@ ROOT="$(realpath $(dirname $BASH_SOURCE)/..)"
 
 set -e
 
+. ${ROOT}/../zephyr/zephyr-env.sh
+
 $ROOT/../zephyr/scripts/twister \
 	--integration \
 	-c \
@@ -15,4 +17,10 @@ $ROOT/../zephyr/scripts/twister \
 	-T tests \
 	-T samples || {
 	echo "Error while trying to build project"
+	exit 1
+}
+
+make -C doc pdf || {
+	echo "Error building documentation"
+	exit 1
 }
