Issue #15: Refactor PDF documentation
## What has been done

Refactor PDF documentation
    
- Add introduction section
- Add a description of the workflow
- Replace getting started guide with workflow
- Cleanup existing documentation
- Add links to discord
- Make sure that documentation build fails if there are any warnings

## Proof

- Downloadable PDF

## Known issues/limitations

- Documentation is still very small and basic.

Closes #15

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -22,8 +22,8 @@ $ROOT/../zephyr/scripts/twister \
 }
 
 # Build documentation
-make -C doc pdf || {
-	echo "Error building documentation"
+${ROOT}/scripts/build-doc || {
+	echo "ERROR: documentation build failed. There are warnings."
 	exit 1
 }
 
