Issue #2: Add initial content
This MR adds initial content as described in https://swedishembedded.com/zephyr-getting-started-directory-structure training.

- Added applications folder
- Added custom board
- Added cmake directory
- Added example driver
- Added empty doc folder
- Added example device tree bindings
- Added include directory
- Added lib directory with example library
- Added example sample
- Added automatic formatting checks
- Added tests directory

- ./scripts/check -a
- ./scripts/build
- ./scripts/fix -a
- robot scrum

* This MR does not add test for 100% code coverage
* This MR does not add documentation tests and doc generation

Closes #2

diff --git a/scripts/check b/scripts/check
--- a/scripts/check
+++ b/scripts/check
@@ -66,3 +66,40 @@ echo -e "---------------------------------------------------"
     echo "Checking compliance failed"
     exit 1
 }
+
+check_file_formatting(){
+	FILE=$1
+	if [[ $FILE == *.py ]]; then
+		black --check $FILE || {
+			echo "Checking formatting of $FILE failed"
+			echo "Run: ./scripts/fix"
+			return 1
+		}
+	elif [[ $FILE == *.c ]] || [[ $FILE == *.h ]]; then
+		clang-format --dry-run --style=file -Werror --fallback-style=none $FILE || {
+			echo "Checking formatting of $FILE failed"
+			echo "Run: ./scripts/fix"
+			return 1
+		}
+	elif [[ $FILE == */CMakeLists.txt ]] || [[ $FILE == *.cmake ]]; then
+		cmake-format --first-comment-is-literal --check $FILE || {
+			echo "Checking formatting of $FILE failed"
+			echo "Run: ./scripts/fix"
+			return 1
+		}
+	fi
+}
+
+# Check file formatting for added and modified files
+for FILE in `git diff --name-status $COMMIT_RANGE | grep "^[AM]" | cut -f 2`; do
+	check_file_formatting $FILE || {
+		exit 1
+	}
+done
+
+# Check file formatting for renamed files
+for FILE in `git diff --name-status $COMMIT_RANGE | grep "^[R]" | cut -f 3`; do
+	check_file_formatting $FILE || {
+		exit 1
+	}
+done
