Issue #22: Add websocket server
## What has been done

This adds websocket server and a visualization example

In this way two or more visualization clients can be connected to the same simulation and it becomes possible to visualize the state of the system very easily. 

## Proof

![image](/uploads/45dde4582f247e594af8bf5727ab983b/image.png)

## Known issues/limitations

- Currently no support for defining custom simulations

Closes #22

diff --git a/scripts/init b/scripts/init
--- a/scripts/init
+++ b/scripts/init
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+ROOT="$(realpath $(dirname $BASH_SOURCE)/..)"
+
 # abort on error (note that this is only a fallback. You should still check
 # return codes every single time!)
 set -e
@@ -15,6 +17,11 @@ fi
 # Initialize the repository
 west init -l .
 west update
+
+# Apply zephyr patches
+$ROOT/scripts/apply-zephyr-patches || {
+	echo "ERROR: Could not apply zephyr patches"
+}
 
 # Install python requirements
 pip3 install -r ../zephyr/scripts/requirements.txt
